# Use Node.js as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the container
COPY package.json ./

# Install dependencies
RUN npm install
RUN npm install -g serve

# Copy the app's source code to the container
COPY . .

# Build the React app
RUN npm run build

# Environment variables
ENV REACT_APP_APP_BASE https://staging-app.omnistudy.io

# Serve the build
CMD ["npx", "serve", "-s", "build"]